#!/bin/sh

set -e

# remove possible existing xdebug configuration from prior execution
rm -f \
  ${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini

# disable APCu for cli
export APCU_ENABLE_CLI=0

# disable OPcache for cli
export OPCACHE_ENABLE_CLI=0

# enable/disable APCu
if [ "${APCU_ENABLE}" = "On" ]; then
    APCU_ENABLE=1
else
    APCU_ENABLE=0
fi

# enable/disable OPCache
if [ "${OPCACHE_ENABLE}" = "On" ]; then
    OPCACHE_ENABLE=1
else
    OPCACHE_ENABLE=0
fi

# enable Xdebug
if [ "${XDEBUG_ENABLE}" = "On" ]; then
    if [ ! -z "${XDEBUG_PROFILER_OUTPUT_DIR}" ]; then
        mkdir -p "${XDEBUG_PROFILER_OUTPUT_DIR}"
    fi

    if [ ! -z "${XDEBUG_TRACE_OUTPUT_DIR}" ]; then
        mkdir -p "${XDEBUG_TRACE_OUTPUT_DIR}"
    fi

    echo "zend_extension=xdebug.so" > ${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini
fi

# first arg is `-v` or `--help`
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
fi

exec "$@"
